test:
  sessions:
    default:
      database: 'datastore-backend'
      hosts:
        - localhost
development:
  sessions:
    default:
      database: 'datastore-backend'
      hosts:
        - localhost
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>